title: Aprendiendo Github
author: Santiago Guerra
email: guerrasantiago19@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Aprendiendo a usar GitHub Pages
# social links
twitter_username: santi_gueam
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
