title: Aprendiendo A usar Github Pages
author: Santiago Guerra
email: guerrasantiago19@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Estoy usando el sitio de Github Learning para poder llevar a cabo este proyecto
# social links
twitter_username: santi_gueam
github_username:  santiagoGuerra

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
